name = "Docker"
type = "webpack"
account_id = "562b498791331089dd53e1df57f41d1b"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "you kv id" }
]
